import { initializeApp } from 'firebase/app';
import { getAuth, signInWithCustomToken } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// Firebase configuration for React Native (Android/iOS)
// Values loaded from environment variables (.env file)
const firebaseConfig = {
  apiKey: process.env.EXPO_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.EXPO_PUBLIC_FIREBASE_APP_ID,
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

/**
 * Authenticates the user with Firebase using a custom token from your backend.
 * @param {string} token - The custom token generated by your backend.
 */
const signInWithCustomFirebaseToken = async (token: string) => {
  try {
    const userCredential = await signInWithCustomToken(auth, token);
    console.log('Successfully signed into Firebase:', userCredential.user.uid);
    return userCredential;
  } catch (error) {
    console.error('Firebase custom sign-in error:', error);
    throw error;
  }
};

export { app, auth, db, signInWithCustomFirebaseToken };