import { initializeApp } from 'firebase/app';
import { getAuth, signInWithCustomToken } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// Your web app's Firebase configuration
// IMPORTANT: Use environment variables for this in a real app
const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

/**
 * Authenticates the user with Firebase using a custom token from your backend.
 * @param {string} token - The custom token generated by your backend.
 */
const signInWithCustomFirebaseToken = async (token: string) => {
  try {
    const userCredential = await signInWithCustomToken(auth, token);
    console.log('Successfully signed into Firebase:', userCredential.user.uid);
    return userCredential;
  } catch (error) {
    console.error('Firebase custom sign-in error:', error);
    throw error;
  }
};

export { app, auth, db, signInWithCustomFirebaseToken };